### ISSUE TITLE
Does the model have facial landmark branch?

### ISSUE THREAD

**Issue by markson14** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#10]
Hi, just wondering does the model have facial landmark output? like 5 keypoints or sth. BTW, this is a great work.

**Comment by Linzaer** [comment]
Sorry, the model doesn't have landmark branch now.

**Comment by hoangtdTcom** [comment]
> Sorry, the model doesn't have landmark branch now.

Do you have ideas for getting landmarks?
