### ISSUE TITLE
使用caffe-SSD进行测试（pytorch转化的caffe模型RFB-320.prototxt和RFB-320.caffemodel）

### ISSUE THREAD

**Issue by Belinda-great** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#104]
@使用pytorch转化的caffe模型RFB-320.prototxt和RFB-320.caffemodel，用caffe-SSD进行测试，出现以下问题，请问有解决方法吗？@Linzaer
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/issues?utf8=%E2%9C%93&q=scores+boxes
![image](https://user-images.githubusercontent.com/20197516/70600621-1a61a600-1c2b-11ea-8a4b-fd30c5a911d8.png)

**Comment by Linzaer** [comment]
你是用我提供的推理代码跑的吗？我这边用caffe-ssd 的python api测试没问题。这个模型是不带detectionout层的，有分数和坐标两个输出，需要后处理代码处理，代码里有。

**Comment by Belinda-great** [comment]
thank you! 不是你提供的推理，直接使用caffe-ssd c++跑的 在RFB-320.prototxt文件最后加了个concat层，连接了boxes和scores，
layer {
  name: "boxes-scores"
  type: "Concat"
  bottom: "boxes"
  bottom: "scores"
  top: "boxes-scores"
  concat_param {
    axis: 2
  }
}
请问这样可以吧？现在可以跑过，但是有太多负分了， 做了后处理，结果好像也不正确

**Comment by Linzaer** [comment]
@Belinda-great 有验证加了concat输出后再分别取出来的结果和pycaffe单独分别取出的结果一致吗？一致的话再看python推理代码的后处理对应改成c++就好了，这部分也可以参考MNN和NCNN中提供的c++后处理代码。

**Comment by Belinda-great** [comment]
@Linzaer 目前还没跑pycaffe的 那我先跑下看看 谢谢啦
