### ISSUE TITLE
服务端mnn，ncnn测试

### ISSUE THREAD

**Issue by reason4** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#105]
在服务端cpu上对mnn和ncnn接口进行了测试，发现mnn比ncnn快2倍左右，请问数据合理吗？另外我用其它tf模型转mnn后，在mnn上跑发现比tf的mkl版本慢很多，也就是说mkl比mnn在服务端cpu上推理更快，是不是意味着如果把ultraface转成tf下的模型，用mkl推理在服务端cpu上会更快呢？谢谢！

**Comment by Linzaer** [comment]
这个模型mnn推理会快。mkl推理你可以试下，我记得支持onnx模型不用转tf，推理速度主要还是看推理框架对用的模型的特定平台下的优化程度。另外ncnn，mnn主要还是针对移动端以及嵌入式设备做加速推理优化的，重点不在pc。mkl属于针对英特尔的平台做专门优化加速的，所以不具备平台可比性，主要还是看你的部署环境。比如gpu环境用tensorrt，intel cpu用mkl或者openvino,边缘设备用mnn、ncnn、mace等。

**Comment by reason4** [comment]
我用mkl尝试一下onnx模型，谢谢！
