### ISSUE TITLE
单核和多核推理时间对比

### ISSUE THREAD

**Issue by jianxiezhendong** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#106]
在rknn上跑MNN下的人脸检测，两个大核为A72。使用单核推理时，时间是每张29ms；使用双核推理时，时间是每张32ms。请问是什么原因呢?谢谢!

**Comment by hosea118** [comment]
进程调度花费时间


jianxiezhendong <notifications@github.com> 于 2019年12月11日周三 下午6:09写道：

**Comment by jianxiezhendong** [comment]
我看了一下您的运行时间，双核跑的时候能达到19ms，您是对进程调度这块做了调整吗?

**Comment by Linzaer** [comment]
@jianxiezhendong 主频多少？用的哪个模型？有多次循环取平均时间吗？

**Comment by jianxiezhendong** [comment]
不好意思，我使用了time.h的时间统计，这个统计方法有问题。换了统计方法，复现了您的速度。感谢!
