### ISSUE TITLE
onnx转caffe时遇到问题

### ISSUE THREAD

**Issue by twq0317** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#107]
File "Ultra-Light-Fast-Generic-Face-Detector-1MB/caffe/onnx2caffe/_operators.py", line 9, in <module>
    from MyCaffe import Function as myf
ImportError: No module named MyCaffe

**Comment by twq0317** [comment]
Hi author, I have figured out the the cause of this issue. I found the origin repository of onnx2caffe, and find that the file 'MyCaffe.py' is missing here. I will send a pull request soon and you can merge it if it's useful ^_^

**Comment by Linzaer** [comment]
Thank you for the issue. I forgot to upload it. I just uploaded it.

**Comment by xautzxc** [comment]
@Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?

**Comment by twq0317** [comment]
> @Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?

转模型前还需要改几行代码，参考 https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn

**Comment by xautzxc** [comment]
> > @Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?
> 
> 转模型前还需要改几行代码，参考 https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn

Thank you so much.

**Comment by xautzxc** [comment]
> > @Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?
> 
> 转模型前还需要改几行代码，参考 https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn

@twq0317 
谢谢，根据你的建议，onnx没有问题了。不过在执行convertCaffe.py遇到了如下的问题：
`(pytorch) librazxc@librazxc-PC:~/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe$ python convertCaffe.py 
Traceback (most recent call last):
  File "convertCaffe.py", line 113, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 67, in convertToCaffe
    layers[id] = layer._to_proto()
  File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: permute_param
`
这个参数错误，你有遇到过吗？我用的是pycaffe，在import caffe是没有问题的。

**Comment by twq0317** [comment]
> > > @Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?
> > 
> > 
> > 转模型前还需要改几行代码，参考 https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn
> 
> @twq0317
> 谢谢，根据你的建议，onnx没有问题了。不过在执行convertCaffe.py遇到了如下的问题：
> `(pytorch) :~/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe$ python convertCaffe.py
> 
> Traceback (most recent call last):
> File "convertCaffe.py", line 113, in convertToCaffe(graph, prototxt_path, caffemodel_path)
> File "convertCaffe.py", line 67, in convertToCaffe layers[id] = layer._to_proto()
> File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 100, in _to_proto assign_proto(layer, k, v)
> File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 29, in assign_proto is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: permute_param
> `
> 这个参数错误，你有遇到过吗？我用的是pycaffe，在import caffe是没有问题的。

需要装 ssd-caffe 和 ssd-caffe版本的pycaffe

**Comment by xautzxc** [comment]
> > > > @Linzaer @twq0317 你好，请问你将***.pth转为onnx再转为caffemodel用的pytorch版本是什么？我将作者提供的pth模型使用torch.onnx->onnx->onnx-simplified简化之后的版本和作者提供的simplified的版本模型输出不一样，boxes输出还是存在slice的op。请问这里的onnx是需使用pytorch0.4吗，我看pytorch1.2 onnx以上支持slice操作?
> > > 
> > > 
> > > 转模型前还需要改几行代码，参考 https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn
> > 
> > 
> > @twq0317
> > 谢谢，根据你的建议，onnx没有问题了。不过在执行convertCaffe.py遇到了如下的问题：
> > `(pytorch) :~/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe$ python convertCaffe.py
> > Traceback (most recent call last):
> > File "convertCaffe.py", line 113, in convertToCaffe(graph, prototxt_path, caffemodel_path)
> > File "convertCaffe.py", line 67, in convertToCaffe layers[id] = layer._to_proto()
> > File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 100, in _to_proto assign_proto(layer, k, v)
> > File "/home/librazxc/Software/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/caffe/MyCaffe.py", line 29, in assign_proto is_repeated_field = hasattr(getattr(proto, name), 'extend')
> > AttributeError: permute_param
> > `
> > 这个参数错误，你有遇到过吗？我用的是pycaffe，在import caffe是没有问题的。
> 
> 需要装 ssd-caffe 和 ssd-caffe版本的pycaffe

@twq0317 
非常感谢，转换成功了。
