### ISSUE TITLE
训练时加载预训练模型出错AttributeError: 'DataParallel' object has no attribute

### ISSUE THREAD

**Issue by zgq91** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#108]
Hi：
     训练的时候 中途有终止, 重新加载之前训练好的模型, 不管是--base_net, --resume, --pretrained_ssd 都会报错"AttributeError: 'DataParallel' object has no attribute

**Comment by lq0104** [comment]
@zgq91 你好，请问你后来解决了吗，我也遇到同样问题了

**Comment by chenti2x** [comment]
@zgq91  我也遇到了相同的问题，请指教。

**Comment by xmadog** [comment]
把代码中初始化DataParallel的过程放在--base_net, --resume, --pretrained_ssd这些操作的最下方
