### ISSUE TITLE
convert MNN model of RFB-640.mnn,but model's box predictions are not right

### ISSUE THREAD

**Issue by 1093842024** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#110]
I follow the instruction of "How to convert pretrained model to MNN".

the first two steps to model version-RFB-640_simplified.onnx works well, and the final step come out a mnn model:
but when i test the mnn model ,the predictions are not right.

To verify the Instruction with no change, I retry the final step of the instruction with your provided model version-RFB-320_simplified.onnx, and get a new RFB-320.mnn, find the new model has the same problem. 

Does that mean the online conversion tools has changed?

**Comment by Linzaer** [comment]
You can try the compiled MNN conversion tool. I use onnx(version 1.6.0), onnx-simplifier(version 0.1.8).

**Comment by 1093842024** [comment]
thx，it's the problem of the MNN conversion tool. I use the compiled MNN tool and solve the problem

**Comment by fengyanWang** [comment]
> thx，it's the problem of the MNN conversion tool. I use the compiled MNN tool and solve the problem

Hello, I have the same problem as you, but after I recompile the MNN conversion tool, it is still the same. How did you compile and solve it
