### ISSUE TITLE
slim训练与测试

### ISSUE THREAD

**Issue by wobjtushisui** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#111]
按照您的训练流程，先过滤数据集、使用默认参数训练了一版slim模型，在val数据集上测试结果和您的结果出入较大，在(320  240)输入图片上我的测试结果为easy: 0.52  medium : 0.35  hard :0.15 ，然后我测试了一下您提供的预训练模型，结果和您给的一致，是不是还有参数没有修改、或者是我过滤数据集的时候出现问题了。您整个训练和测试代码我都认真学习了一下，iou_threshold参数设置为0.35训练的模型会不会误检比较多，损失函数部分加入landmark和focal loss 准确度应该会更高。谢谢帮忙解答！

**Comment by Linzaer** [comment]
按道理不应该这么低。你看下你过滤的数据集结果和我给的出入大吗，比如图片数量，地标框是否对。你或者用我给的数据集训练一下对照看看，如果正常那就是数据集问题。overlap_threshold设置为0.35会提供多一点正样本训练，不过可能会出现一定的框漂，特别是小物体，我试下来0.35还可以，你也可以都试试测下widerface，结果好才是好。加了lm的版本之前测试几个版本效果不太好，暂时不提交，最近比较忙哈。focal loss你可以试试，不过在这个模型上效果不一定好。

**Comment by wobjtushisui** [comment]
好的非常感谢，我下载您的数据集再测试试试
