### ISSUE TITLE
特征图与anchor匹配问题

### ISSUE THREAD

**Issue by hajungong007** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#113]
你好，请问stride 16 和32特征图上每个像素点生成的anchor数是2个，最后定位和分类的的out_channels=3 * num_classes，这样为什么不会出问题啊？我理解应该为out_channels=2 * num_classes才正确

**Comment by Linzaer** [comment]
你看错了....你再仔细看看
