### ISSUE TITLE
Publish C# version

### ISSUE THREAD

**Issue by takuya-takeuchi** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#123]
Hi @Linzaer 

I cretead C# version of Ultra-Light-Fast-Generic-Face-Detector-1MB.
https://github.com/takuya-takeuchi/UltraFaceDotNet

What do you think about?
Please notify if there is any issue, e.g. license.

**Comment by Linzaer** [comment]
@takuya-takeuchi Great job! Thanks for your open source!

**Comment by takuya-takeuchi** [comment]
@Linzaer 
Thank you, too!

**Comment by Linzaer** [comment]
I'll add this link to the readme.
