### ISSUE TITLE
version-RFB-320 convert2caffe

### ISSUE THREAD

**Issue by Belinda-great** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#128]
Hi  如果使用模型version-RFB-320_simplified.onnx convert2caffe是没问题的，如果version-RFB-320.onnx convert2caffe就出现以下问题：
![image](https://user-images.githubusercontent.com/20197516/71810422-54e52400-30ad-11ea-93b7-021c6b7054aa.png)
请问是什么原因那？

**Comment by yjhuasheng** [comment]
可以参考这个，https://github.com/daquexian/onnx-simplifier

**Comment by Linzaer** [comment]
需要onnx-simplifier 简化冗余算子
