### ISSUE TITLE
/models/onnx/version-RFB-320.onnx和version-RFB-320_simplified.onnx有错误

### ISSUE THREAD

**Issue by HollrayChan** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#136]
作者你好，我在用detect_imgs_onnx.py去运行以上的两个onnx模型的时候，发现version-RFB-320_simplified.onnx的结果是乱七八糟的(错误的结果)。然后我用onnx-simplifier转version-RFB-320.onnx之后，结果才是正确的，是上传错了吗 :P
![20200115163330](https://user-images.githubusercontent.com/50159625/72418154-45ed2880-37b5-11ea-9f8d-689b6ee53ec8.png)

**Comment by HollrayChan** [comment]
对了，还有caffe里面的权重也是

**Comment by lishiyuwhu** [comment]
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/issues/49  
我猜是这个问题.

**Comment by HollrayChan** [comment]
ok 明白了~谢谢:)~

**Comment by HollrayChan** [comment]
ok 明白了谢谢 :)~

**Comment by Linzaer** [comment]
@HollrayChan @lishiyuwhu 对的。
