### ISSUE TITLE
The result box's width is smaller than my face.

### ISSUE THREAD

**Issue by GHLab** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#141]
Hi,
The result box's width is smaller than my face and the height is litte big so bottom line is under my chin.
Because of this, landmark result is not good. (I used the other landmark model)
I tested it by ncnn version.
How can I solve this?

**Comment by Linzaer** [comment]
What is the resolution of the input? Which model you use？

**Comment by GHLab** [comment]
@Linzaer The input size is 128x96 and used slim model. I have to use small input size for speed.

**Comment by Linzaer** [comment]
Because of the slim-320 model is trained in 320x240 , and image preocessing have no pad magin ,so the box will be  a little bit offset  when you use 160x96 input resolution.

**Comment by GHLab** [comment]
@Linzaer OK. I will add some margin. Thank you!
