### ISSUE TITLE
Minimum boxes

### ISSUE THREAD

**Issue by krishnak** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#147]
In ultraface_py_mnn.py

min_boxes = [[10, 16, 24], [32, 48], [64, 96], [128, 192, 256]]
strides = [8, 16, 32, 64]

Is there any literature available to understand what are  these values and how are they arrived, or can you please explain yourself if its simple to explain

**Comment by Linzaer** [comment]
The size of anchor boxes corresponding to each detecttion layer. You can refer to the paper of ssd.

**Comment by krishnak** [comment]
I have read the paper, I understand that you are having unequal number of boxes per each detection layer. 

How were these numbers arrived at, for example 10,16,24 for the tiny layer will produce 10/240,10/320 etc for box width.
