### ISSUE TITLE
关于BGR2RGB

### ISSUE THREAD

**Issue by lq0104** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#148]
您好，感谢您分享的这个项目，真的很厉害！还有一个问题想请教您，因为opencv正常读图像是BGR格式，而在这个项目中训练之前我有注意到图像都使用了BGR2RGB转成了RGB格式，而在您提供的pytorch，caffe，onnx，ncnn还有mnn都在进行推理前也进行了BGR2RGB的转换
我的问题是，如果只要保证训练和推理用的策略相同，那么就都不转换了，用BGR格式训练、再用BGR格式推理不就行了，转换成RGB格式有什么特殊的意义吗？

**Comment by Linzaer** [comment]
bgr可以的，训练和推理一直就行。
