### ISSUE TITLE
building with MNN on windows 

### ISSUE THREAD

**Issue by HosseynGT** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#149]
Could you please help me to run "Ultraface" on windows. When I want to build it, get this error:
UltraFace.obj : error LNK2019: unresolved external symbol "public: __cdecl MNN

thanks

**Comment by Linzaer** [comment]
Sorry, I didn't run MNN version of ultraface on windows ,maybe you can look at the issues of mnn's github.
