### ISSUE TITLE
onnx 转换 ncnn 问题

### ISSUE THREAD

**Issue by starasking** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#152]
您好，我想测试一下人脸检测 ncnn 的程序，出现了一些问题：
1. 首先，用 ncnn/data/version-RFB 中的 RFB-320.bin   RFB-320.param 去测试 UltraFace，程序运行并检测成功。
2. 按照 .pth => onnx => onnx_simplified => ncnn 的流程来做
    1） 成功生成 onnx，并人脸检测成功。
    2） onnx => onnx_simplified
    3） 用 ncnn build 生成的 RFB-320_build.bin   RFB-320_build.param，可以提取 scores, 但无法提取 boxes，两个 param 文件显示以下区别
![image](https://user-images.githubusercontent.com/44088071/74799679-22655280-530c-11ea-902b-f2247f9cbef6.png)
   4） 用 https://convertmodel.com/?tdsourcetag=s_pctim_aiomsg 生成的 RFB-320_online.bin   RFB-320_online.param 文件去 跑 UltraFace，会显示内存问题
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/44088071/74799650-0feb1900-530c-11ea-80e2-486bc3c199d1.png">

其中用到的命令是：
1. python convert_to_onnx.py
2. python3 -m onnxsim version-RFB-320.onnx version-RFB-320_simplified.onnx
3. onnx2ncnn version-RFB-320_simplified.onnx RFB-320_build.param RFB-320_build.bin

我想问一下，怎么生成正确的 ncnn 模型部分？

**Comment by mathpopo** [comment]
@starasking hi,请问下怎么解决的，我也遇到了同样的问题

**Comment by starasking** [comment]
提取 460 的数据 instead of "boxes"

mathpopo <notifications@github.com> 于2020年6月4日周四 上午11:23写道：

**Comment by fengyanWang** [comment]
我在ONNX转MNN模型也遇到了问题，人脸检测精度会明显下降
