### ISSUE TITLE
树莓派4 安装MNN

### ISSUE THREAD

**Issue by Jzz24** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#161]
你好，想请问如何在树莓派4上安装MNN，我通过pip始终无法找到MNN

**Comment by Linzaer** [comment]
源码编译

**Comment by Jzz24** [comment]
我按照官网进行编译 https://www.yuque.com/mnn/en/build_linux#tnpNk 
但是总是报如下错误，请问我有哪些需要注意吗？
[ 38%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/ThreadPool.cpp.o
[ 38%] Built target MNNCPU
make: *** [Makefile:130: all] Error 2

**Comment by Jzz24** [comment]
你好，我用单线程 从源码编译，始终报这个错误，想问一下你的树莓派系统配置是怎样的？
[ 37%] Building ASM object CMakeFiles/MNNARM32.dir/source/backend/cpu/arm/arm32/MNNAddBias.S.o
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S: Assembler messages:
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:28: Error: selected processor does not support `vld1.32 {q15},[r1]!' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:37: Error: selected processor does not support `vld1.32 {q0,q1},[r5]!' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:38: Error: selected FPU does not support instruction -- `vadd.f32 q0,q0,q15'
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:39: Error: selected processor does not support `vld1.32 {q2,q3},[r5]' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:40: Error: selected FPU does not support instruction -- `vadd.f32 q1,q1,q15'
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:41: Error: selected FPU does not support instruction -- `vadd.f32 q2,q2,q15'
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:42: Error: selected processor does not support `vst1.32 {q0,q1},[r0]!' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:43: Error: selected FPU does not support instruction -- `vadd.f32 q3,q3,q15'
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:44: Error: selected processor does not support `vst1.32 {q2,q3},[r0]!' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:53: Error: selected processor does not support `vld1.32 {q0},[r0]' in ARM mode
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:54: Error: selected FPU does not support instruction -- `vadd.f32 q0,q0,q15'
/home/pi/MNN/source/backend/cpu/arm/arm32/MNNAddBias.S:56: Error: selected processor does not support `vst1.32 {q0},[r0]!' in ARM mode
make[2]: *** [CMakeFiles/MNNARM32.dir/build.make:63: CMakeFiles/MNNARM32.dir/source/backend/cpu/arm/arm32/MNNAddBias.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:625: CMakeFiles/MNNARM32.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Jzz24** [comment]
通过降低版本，已解决

**Comment by zaiyebuheniwanle** [comment]
> 通过降低版本，已解决

编译成功可以import吗？

**Comment by Jzz24** [comment]
可以的

**Comment by zaiyebuheniwanle** [comment]
> 可以的

不好意思，能说一下详细流程吗？我按照文档来能编译成功却不能import
