### ISSUE TITLE
以320尺寸训练的模型如何在使用时推理480尺寸的图片？

### ISSUE THREAD

**Issue by urbaneman** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#163]
如题，按照您readme里写的：
> （2）次优：输入尺寸input_size：320（320x240）分辨率训练，并采用480x360或640x480大小输入进行预测推理，对于小人脸更敏感，误报会增加。

在通过convert_to_onnx.py转化成onnx时如何使用？
尝试修改[代码](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/029907032ba408fc57a829c430d5bd3936e3cae7/convert_to_onnx.py#L41) 

> dummy_input = torch.randn(1, 3, 240, 320).to("cuda")

to
> dummy_input = torch.randn(1, 3, 320, 480).to("cuda")

转换失败

您是怎么做的？

**Comment by Linzaer** [comment]
convert_to_onnx.py中第十行的 input_img_size = 320 需要改一下，480x360输入的话改成480，640x480的话改成640，这边决定锚点候选框的数量。

**Comment by urbaneman** [comment]
感谢，抱歉没有认真读您的代码，已解决，麻烦您了。
