### ISSUE TITLE
JavaCV Example running with 40 FPS

### ISSUE THREAD

**Issue by cansik** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#168]
Because I had some struggle with running it in OpenCV (by using JavaCV) I just provide my example here. The code adapts some python code provided in the repo, but tries to optimise it as good as it can.

https://github.com/cansik/deep-vision-processing/blob/b8cea3975559f9927fa37b493fcc6fb89fce7a6c/src/main/java/ch/bildspur/vision/ULFGFaceDetectionNetwork.java#L65

**Comment by Linzaer** [comment]
@cansik Thanks for your good job!

**Comment by cansik** [comment]
There is one problem when trying to load the `version-RFB-640.onnx` model in OpenCV:

```
Input is out of OpenCV 32S range in function 'convertInt64ToInt32'
```

This is due a [not yet implemented](https://github.com/opencv/opencv/issues/14984) Int64 support in the DNN module. Running the `version-RFB-320_simplified.onnx` model works without any problems, I guess because the post-processing is stripped away, as described by you [here](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/ncnn/README.md#how-to-convert-pretrained-model-to-ncnn).

Now the problem is that I am running the network on a MacBook Pro (without CUDA support), but the ONNX converter is using CUDA. Is it possible to remove the dependency somehow or could you provide a simplified version as well for the 640 model?

**Comment by cansik** [comment]
Ok, never mind, I've already figured it out:

- Change device to `cpu`
- Remove all the `.cuda()` methods

**Comment by xuguozhi** [comment]
> Ok, never mind, I've already figured it out:
> 
> * Change device to `cpu`
> * Remove all the `.cuda()` methods

I have met "Input is out of OpenCV 32S range in function 'convertInt64ToInt32'" too.
