### ISSUE TITLE
Raspberry Pi 4b OS choice

### ISSUE THREAD

**Issue by liuwuliuyun** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#19]
Hi, 
thanks for the great work, I 'd like to ask what is your OS choice on Raspberry Pi 4b ? Cuz 32-bit OS like Raspbain will encounter cross compiling issue when setting up MNN inference tool. Or your choice is to get a different cross compiling tool that works on 32-bit OS.

Thanks again for your answer!

**Comment by Linzaer** [comment]
@liuwuliuyun Thanks.I use the official 32-bit OS Raspbian on Raspberry Pi 4b and  I compile MNN locally without  cross compiling.Maybe you can try it.

**Comment by liuwuliuyun** [comment]
That did work out for me, thanks a lot 💃

**Comment by Linzaer** [comment]
@liuwuliuyun ^-^
