### ISSUE TITLE
该人脸检测方法是基于哪篇论文实现的？

### ISSUE THREAD

**Issue by 205418367** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#21]
是基于SSD+RBFNet进行人脸检测？我想读一下论文。

**Comment by Linzaer** [comment]
优化落地项目，没有论文。

**Comment by 205418367** [comment]
我看代码里面有ssd和rbfnet，我想应该是基于这两个方法训练的人脸检测方法。此外，你做了哪些优化？

**Comment by Linzaer** [comment]
主干裁剪瘦身、anchor设计修改、检测分支裁剪、数据集优化、RFB修改、预处理数据增强优化之类的。

**Comment by 205418367** [comment]
如果能分享一下如何优化的就太棒了。

**Comment by Linzaer** [comment]
可以看代码的，里面都有。

**Comment by 205418367** [comment]
在实际落地时不需要用到人脸关键点？有没有考虑过把人脸关键点检测加入到网络中？

**Comment by Linzaer** [comment]
数据集关键点已经清理出来了，有空会考虑加上，估计效果可能不会太好受限于网络。不过一般在实际场景第一个最前面的检测网络会出现误检或者模糊的人脸不利于后续的识别之类的，可以配合一个输入很小的带五点关键点的小快检测网络来做二次过滤和出五点做对齐，类似一个人脸质量检测网络，过滤一些不良人脸，效果会更加好一点，也是一个解决方案哈，不过运算量会有波动哈。

**Comment by 205418367** [comment]
为什么在训练时需要设置输入图片的尺寸，一般目标检测算法的训练集不需要固定尺寸的图片作为输入吧？

**Comment by Linzaer** [comment]
@205418367 一般都要的吧，虽然一般都是全卷积网络对输入大小没限定，但是gpu并行训练的一个batch都要一样的尺寸方便加速，个人认为统一resize对一般的检测影响不太大，而且anchor的设计也会比较方便。

**Comment by 205418367** [comment]
因为有roi pooling的存在，faster rcnn 等算法在训练时不需要统一图片的尺寸作为输入。

**Comment by 205418367** [comment]
刚刚查了一下文档，ssd算法的输入必须统一尺寸

**Comment by Linzaer** [comment]
@205418367 这种属于背课文说法..

**Comment by 205418367** [comment]
source_layer_indexes = [8,11,13]
self.source_layer_add_ons = nn.ModuleList([t[1] for t in source_layer_indexes
                                                   if isinstance(t, tuple) and not isinstance(t, GraphPath)])
这两行代码是什么意思？t显然是int类型，

**Comment by 205418367** [comment]
你说的主干网络就是指下面这两个网络吧？
mb_tiny.py
mb_tiny_RFB.py
