### ISSUE TITLE
针对大脸检测效果不好? models: Mb_Tiny_FD_train_input_320.pth

### ISSUE THREAD

**Issue by Belinda-great** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#23]
Hi 非常感谢你的贡献！ 请问models: Mb_Tiny_FD_train_input_320.pth 是不是对大脸检测效果比较差 使用detect_imgs.py进行测试， 参数未做任何修改。

**Comment by Belinda-great** [comment]
![12058](https://user-images.githubusercontent.com/20197516/66983928-49a4dc80-f0ec-11e9-9552-c494cbfede56.jpg)
![18607](https://user-images.githubusercontent.com/20197516/66983951-54f80800-f0ec-11e9-84c3-a4b643f1d776.jpg)
![12058](https://user-images.githubusercontent.com/20197516/66984006-72c56d00-f0ec-11e9-8ac4-ed91d548756e.jpg)
![18607](https://user-images.githubusercontent.com/20197516/66984007-72c56d00-f0ec-11e9-9fe2-392618127e26.jpg)

**Comment by Linzaer** [comment]
输入可以成320或者更小试下

**Comment by summerwbb** [comment]
你好，请问您出来的结果稳定吗？我现在训练的结果测试图片容易丢帧和回归效果不准确的情况。 @Belinda-great @Linzaer

**Comment by Linzaer** [comment]
@summerwbb 网络类型？训练输入大小？和提供的预训练模型效果差别大吗？测试时输入多大？如果测试图片人脸很多很小的话，适当减小候选框数值保证有效人脸。

**Comment by summerwbb** [comment]
我使用的RFB网络训练了一个人头检测模型（使用train_mb_tiny_RFB_fd.sh脚本，只改变了数据），训练和测试输入大小是640，测试时候选框改成了150个，是普通的电影素材。多数是不超过5个。请问我的loss应该降低到大概多少才是收敛了.
![image](https://user-images.githubusercontent.com/40291885/67094721-ee0b4980-f1e6-11e9-8651-bc9ef3c8b082.png)
![image](https://user-images.githubusercontent.com/40291885/67094742-f95e7500-f1e6-11e9-84f6-3461d214b79c.png)
![image](https://user-images.githubusercontent.com/40291885/67094767-0a0eeb00-f1e7-11e9-9996-8824c979adb7.png)
![image](https://user-images.githubusercontent.com/40291885/67094919-535f3a80-f1e7-11e9-9392-ed13c5e725e8.png)

**Comment by summerwbb** [comment]
我也同时训练了320 版本，感觉640更适合我的场景。

**Comment by Linzaer** [comment]
用smooth_l1_loss，320x240训练人脸，200epochs最后大概稳定在2.84左右，640x480大概稳定在2.57左右，仅供参考。你数据集图片数有多少？很大可能和数据集数量和质量有关。你也可以尝试修改下预处理阶段的流程，比如加入Expand方法，扩张原图加强小目标能力，也可以略微修改randomcrop里的纵横比和交并比增强检测大目标能力。当然你也可以略微重复一两个不影响featuremap尺度的block加强网络主干。
