### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'SSD' object has no attribute 'module'

### ISSUE THREAD

**Issue by shashitechno** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#238]
Any thoughts what's wrong here?

**Comment by shashitechno** [comment]
Found this was a typo and modules can be removed!

**Comment by legendlc** [comment]
> Found this was a typo and modules can be removed!
> 
> Regards
> https://findmyfbid.in

Actually if you are using cuda, it's totally ok, because net is constructed by DataParallel; but if you use cpu, this error will be thrown because net is just nn.Module

**Comment by torta24x** [comment]
Just to add to @shashitechno 
As I was using older repo commit file I had this issue.

```
# if using GPU 

net.module.save(model_path)     # Change this
net.save(model_path)            # to this
```

Thanks
