### ISSUE TITLE
训练的数据增强里我看你crop的都是长宽比1：1的，然后直接resize成320*240这种比例，为啥输入的比例是320*240这种的，不应该方形更符合数据增强的策略吗

### ISSUE THREAD

**Issue by allenwangcheng** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#24]

**Comment by Linzaer** [comment]
输入原图一般是16:9，缩放形变小。crop是原图正方形，之后resize训练，坐标都是按比例的，影响不大，而且320x240推理速度还快点。

**Comment by allenwangcheng** [comment]
测试的时候输入是16：9的然后resize成320*240，训练的时候等于是1：1的resize成320*240，等于训练和测试的时候输入分别是1：1和16：9，感觉这个形变还是很大的吧

**Comment by Linzaer** [comment]
有一定的形变，但是h/w=1 的几率是很小的，你也可以认为这边几乎没做randomcrop来加强大图，反而一定程度上可以略微加强鲁棒性。也改过其他的纵横比，效果差不多，当然你可以试下2/3<w/h<3/2的比率或者输入变为320x320正方形训练，不过这样计算量要大30%，精度应该会提升一点。
