### ISSUE TITLE
pc上测试时间问题

### ISSUE THREAD

**Issue by Belinda-great** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#25]
Hi 请教下 pc: win7 cpu E5-1603 2.80GHz ,net_type: mb_tiny_fd, input_size:320,图片大小为320*240，测试14张图片，平均时间为：203ms, 请问测试的时间对吗？cpu下感觉时间有点长。

**Comment by Linzaer** [comment]
不太正常哈，一般pytorch用cpu测的话十几ms吧

**Comment by Belinda-great** [comment]
> 不太正常哈，一般pytorch用cpu测的话十几ms吧
检查了好久 没发现是哪的原因？大概可能的原因能给点建议吗？谢谢啦

**Comment by Belinda-great** [comment]
> 不太正常哈，一般pytorch用cpu测的话十几ms吧

检查了好久 没发现是哪的原因？大概可能的原因能给点建议吗？谢谢啦

**Comment by Linzaer** [comment]
测试的是前向传播时间还是处理一张照片的全部流程时间？

**Comment by Belinda-great** [comment]
> 测试的是前向传播时间还是处理一张照片的全部流程时间？

测试的只是前向传播的时间。 `self.timer.start()
                scores, boxes = self.net.forward(images)
                print("Inference time: ", self.timer.end())`

**Comment by Linzaer** [comment]
同等硬件配置的情况下，你有试过在linux环境下的速度吗？

**Comment by Belinda-great** [comment]
> 同等硬件配置的情况下，你有试过在linux环境下的速度吗？

没有 目前没有Linux系统

**Comment by Linzaer** [comment]
也很有可能是pytorch 的cpu版本对老款志强服务器cpu的算子优化不好。
