### ISSUE TITLE
Face Detector deployed on Android with tflite

### ISSUE THREAD

**Issue by Zeleni9** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#259]
Hey, 

I have seen that there is tflite model without post processing which sounds great, but I am still not sure how to gather outputs of the model in Java/Kotlin code. Below I have added Kotlin code that has problems with getting outputs in good fromat. Maybe you have some idea how to properly get it. I have inspected model with https://netron.app/ and saw input/output formats. 

If I read outputs of the model in app and in Intepreter I get [1][1][4] and [1][1][2] and when I run the model I get TensorFlowLite tensor (Identity) with shape [1, 4420, 4] that cant fit into a Java object with shape [1, 1, 4].

Error: 
    java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 4420, 4] to a Java object with shape [1, 1, 4].

Thank you!

```
class UltraFastFaceDetector {

    lateinit var model: Interpreter

    public fun init(context: Context) {
        val modelFile = FileUtil.loadMappedFile(context, "version-RFB-320_without_postprocessing.tflite")
        // Initialize interpreter with GPU delegate
        val options = Interpreter.Options()
        options.setNumThreads(4)
        model = Interpreter(modelFile, options);
    }

    public fun predict(input: Bitmap, context: Context): Float {
        // Resize Bitmap to 240x320
        val imageArray = convertBitmapToByteArray(input)

        val lastIndex = imageArray!!.size
        val b =  BitmapFactory.decodeByteArray(imageArray, 0, lastIndex)
        var bitmap = Bitmap.createScaledBitmap(b, 240, 320, false)

        // Read input of the model data type and shape
        val imageDataType = model.getInputTensor(0).dataType()
        val inputShape = model.getInputTensor(0).shape()
        val image = TensorBuffer.createFixedSize(inputShape, imageDataType)
        var tensorImage = TensorImage(imageDataType)
       
   
         // Preprocessor for preparing image
        val imageProcessor = ImageProcessor.Builder()
                .add(NormalizeOp(127.5f, 127.5f)) // scales to [-1, 1]
                // .add(NormalizeOp(1.0f, 255.0f))                 // scales to [0, 1]
                .build()

        // Preprocess the input bitmap
        tensorImage.load(bitmap)
        tensorImage = imageProcessor.process(tensorImage)

        // Output of model [1][1][4] & [1][1][2]
        val loc = Array(1) { Array(1) { FloatArray(4) } }
        val cla = Array(1) { Array(1) { FloatArray(2) } }

        val outputs: MutableMap<Int, Any> = HashMap()
        outputs.put(model.getOutputIndex("Identity"), loc)
        outputs.put(model.getOutputIndex("Identity_1"), cla)
        model.runForMultipleInputsOutputs(arrayOf(tensorImage.buffer), outputs)

        return outputs
    }


        // Run prediction with model
        model.run(tensorImage.buffer, outputs.buffer)

       return outputs
    }
}
```

**Comment by mozhdehnoori** [comment]
hi dear
you have 2 output one for shape and two for your score 
first you need define your output like this

var output1 = Array(1) {
        Array(4420) {
            FloatArray(4)
        }
    }

    var output2 = Array(1) {
        Array(4420) {
            FloatArray(2)
        }
    }

   val outputs: MutableMap<Int, Any> = HashMap()
        outputs[0] = output1
        outputs[1] = output2

and second you need to define output look like this:

you need use  model.runForMultipleInputsOutputs(arrayof(inputArray), outputMap);
