### ISSUE TITLE
ONNX模型导入到TensorRT报错。

### ISSUE THREAD

**Issue by saladjay** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#26]
![image](https://user-images.githubusercontent.com/26593079/67006131-e0868e80-f116-11e9-8fde-2d9c9ef5c0bc.png)
模型是Mb_Tiny_RFB_FD_train_input_640.pth

**Comment by saladjay** [comment]
一般情况下，ONNX导入到TensorRT报这个错误，是因为pytorch使用了view层。但是我去看代码，没有找出view层在哪里。

**Comment by Linzaer** [comment]
compute_header里有view，你可以用onnx-simplifier 生成精简onnx试下。

**Comment by saladjay** [comment]
![image](https://user-images.githubusercontent.com/26593079/67083233-5e0cd600-f1cd-11e9-99f4-49a41a6a9505.png)
我解决上面那个的问题，在compute_header中使用view(int(num1),num2)这种方式解决。
接下来slice操作报错了。slice对应pytorch的tensor取区间操作。我反复查看了pytorch的代码，没发现越界的问题。不知道怎么解决。

**Comment by saladjay** [comment]
![image](https://user-images.githubusercontent.com/26593079/67083891-8c3ee580-f1ce-11e9-9db6-7fac2a1aaf94.png)
![image](https://user-images.githubusercontent.com/26593079/67084073-dc1dac80-f1ce-11e9-9ff9-14fa753cfe6e.png)

**Comment by Linzaer** [comment]
@saladjay tensorRt没怎么用过，不过你说的这部分属于后处理代码部分，数学算子比较多一点，各个框架之间算子转换兼容性比较容易出问题。其实你可以在导出onnx的时候注释掉ssd.py中调用convert_locations_to_boxes()和center_form_to_corner_form()这两处，应该是第95~98行，让推理框架只负责提取特征，输出上面boxes偏移量就好，框解码部分的后处理代码可以用c++写，不是很复杂，可控速度也不慢优化程度高。而且推理框架处理这段可能效果反而不太好，不太可控。

**Comment by saladjay** [comment]
![image](https://user-images.githubusercontent.com/26593079/67137453-2d2daf00-f268-11e9-99d0-43e6523a00b5.png)
像这种就能成功pytorch->onnx->tensorRT。同时在pytorch->onnx的过程中最好不要使用像[:,0:2,:]的操作，最好每个维度都给出确定的数字，除了batch。希望能帮到同样像导出tensorRT的人。

**Comment by saladjay** [comment]
你好，作者，请问你是用什么数据集训练的。现在打算在原工程上改动预测框的计算方式，重新训练一下。方便讲解一下训练数据集和训练策略吗。

**Comment by atanx** [comment]
> ![image](https://user-images.githubusercontent.com/26593079/67137453-2d2daf00-f268-11e9-99d0-43e6523a00b5.png)
> 像这种就能成功pytorch->onnx->tensorRT，截取的区间不要是最后一个维度。同时在pytorch->onnx的过程中最好不要使用像[:,0:2,:]的操作，除了batch，最好每个维度都给出确定的数字。希望能帮到同样像导出tensorRT的人。

遇到一样的问题。
```
In node 76 (convert_axis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
```
能详细讲一下怎么转tensorrt模型吗？

**Comment by saladjay** [comment]
> 像这种就能成功pytorch->onnx->tensorRT，截取的区间不要是最后一个维度。同时在pytorch->onnx的过程中最好不要使用像[:,0:2,:]的操作，除了batch，最好每个维度都给出确定的数字。希望能帮到同样像导出tensorRT的人。
> 
> 遇到一样的问题。
> In node 76 (convert_axis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
> 
> 能详细讲一下怎么转tensorrt模型吗？

view改flatten或者view的第一个参数强制转换为int类型
