### ISSUE TITLE
MNN量化模型（slim-320-quant-ADMM-50.mnn）在GPU（OPENCL）上跑没有结果

### ISSUE THREAD

**Issue by xxssd-awsl** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#261]
我用MNN那个文件夹在的文件写了个Android实时检测的demo，测试了两个模型，一个slim-320.mnn，一个slim-320-quant-ADMM-50.mnn，两个模型在CPU上跑都没问题，slim-320.mnn能在opencl上跑但是slim-320-quant-ADMM-50.mnn在opencl上跑每一帧都没有结果，请问为什么，我甚至把阈值设置为0.001了

**Comment by xxssd-awsl** [comment]
没事了，在MNN官方文档找到了：
// Option 2: 如需运行量化模型以运用INT8 SDOT加速，选择普通精度（默认值）
backendConfig.precision = BackendConfig::Precision_Normal;

**Comment by liuqinglong110** [comment]
> 

你好，请问使用MNN+opencl编译ultraface这个工程后，运行的时候，有没有遇到“not support dimensions == 3”问题呢？我看到其他人遇到了类似问题，无法解决。https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/issues/95
