### ISSUE TITLE
Good job! How to change the setting as I want run this algorithm in cpu mode.Thanks!

### ISSUE THREAD

**Issue by zyg11** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#3]

**Comment by Linzaer** [comment]
For example,in the file 'detect_imgs.py',you can change varaible 'test_device' from 'cuda:0' to "cpu".Then,it will run in cpu mode.

**Comment by zyg11** [comment]
I got it ! Thanks again!
