### ISSUE TITLE
Wider face test or val?

### ISSUE THREAD

**Issue by biubug6** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#30]
感谢你的工作! 麻烦请问一下测试的时候是在widerface val(官方公布了标注文件)进行测试的么? widerface test数据集官网没有放出来标签,评测的话一般是需要提交txt文件给官方代为评测.

**Comment by Linzaer** [comment]
@biubug6 感谢你的反馈，这边的确是笔误了，是在matlab上测的widerfac val集合，文档已经修正。

**Comment by biubug6** [comment]
谢谢你的回复, 顺便再问一下slim 和RFB版本评测的时候图片尺寸也是按照最大边等比例缩放么, 还是固定成640*480 or 320*240 这两种评测方式结果应该影响不大吧?

**Comment by Linzaer** [comment]
训练是固定640x480或者320x240训练的，所以测试也是固定尺寸resize的，这样比较贴近训练场景，性能损失小。retinaface是等比缩放训练的，所以测试也采用等比缩放，尽力保证在这个尺度下测试性能，人脸不形变。这样尽量保证都在相对鲁棒的方式下测试。

**Comment by biubug6** [comment]
谢谢解惑
