### ISSUE TITLE
RandomSampleCrop_v2

### ISSUE THREAD

**Issue by yantiantianlx** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#32]
实际没有采用任何crop操作？ 为什么？ 故意不采用么？

**Comment by Linzaer** [comment]
其他纵横比crop效果不好

**Comment by yantiantianlx** [comment]
![1](https://user-images.githubusercontent.com/24607440/67172086-8de5f480-f3ec-11e9-9d9f-12aa8f681bcb.png)

在该函数中，if h/w != 1 一直成立（h，w为随机的小数，未进行int操作，h/w==1难以满足）， 一直执行continue, 直到采样mode==None(即不执行任何crop操作)， 函数return。 因此该函数未执行crop操作。
