### ISSUE TITLE
RandomSampleCrop_v2问题

### ISSUE THREAD

**Issue by yantiantianlx** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#38]
![1](https://user-images.githubusercontent.com/24607440/67172262-401dbc00-f3ed-11e9-92ae-1b9188f09086.png)

在该函数中，if h/w != 1 一直成立（h，w为随机的小数，未进行int操作，h/w==1难以满足）， 一直执行continue, 直到采样mode==None(即不执行任何crop操作)， 函数return。 因此该函数未执行crop操作。

**Comment by Linzaer** [comment]
是的，这边其实没有crop，你可以放宽一点h/w纵横比范围，比如2/3<h/2<3/2,我试验下来loss要高一些，所以我这边设置了1基本上等于没crop。
