### ISSUE TITLE
关于模型量化

### ISSUE THREAD

**Issue by zyc4me** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#4]
非常棒的工作！
关于mnn量化的模型，你这里给出了前向的时间，想问下量化后的检测精度怎样呢？下降程度大吗?注意到你骨干类似mobilenetv1， 为何不用带残差的v2 v3类似结构？

**Comment by Linzaer** [comment]
感谢支持，最近比较忙哈，在todolist 中之后会做相关的测试和代码~
v2我改过几版本，同等大小和计算量效果不太好，可能是主干和分支设计组合还没到最好，感兴趣的话你可以尝试下哈，欢迎互相交流哈~

**Comment by ddcat1991** [comment]
@Linzaer 请问一下作者大人, 树莓派里用的量化是怎么做的呢？ 是拿到的onnx模型转成caffe再做int8量化吗?

**Comment by Linzaer** [comment]
@ddcat1991 onnx 转mnn或者ncnn框架文件格式，然后用推理框架各自提供的int8量化工具量化。
