### ISSUE TITLE
failed to convert *.pth to ncnn model 

### ISSUE THREAD

**Issue by wjgarnett** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#44]
你好，我尝试将预训练中的*.pth模型按说明中的先修改源代码转为onnx后，无法将该onnx模型通过onnx simplifier转换为新的onnx模型，想确认下你工程中给出的转换流程是否如下：
1.按说明修改源代码，执行convert_to_onnx将.pth模型转为onnx模型
2.用onnx simplifier工具将onnx模型转换为onnx_sim模型
3.编译ncnn,利用ncnn中tools/onnx下的转换工具将onnx_sim模型转换为对应的NCNN模型

**Comment by wjgarnett** [comment]
谢谢，在线的我也试过。 我的应该是转onnx/onnx_sim过程中出了问题，我用的win10系统。我试试在linux下转。

**Comment by wjgarnett** [comment]
谢谢，已解决！

**Comment by leiyu1980** [comment]
咋解决的啊。

**Comment by wjgarnett** [comment]
> 咋解决的啊。

我从win10切换到ubuntu16.04解决的。
