### ISSUE TITLE
pytorch 转onnx

### ISSUE THREAD

**Issue by mjanddy** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#47]
你好，我想问一下，为什么pytroch转为onnx模型后，不需要重写生成框的代码呢？而ncnn就需要。

**Comment by Linzaer** [comment]
pc的onnx导出时包含了解码框操作，导出到ncnn时由于算子兼容和精度问题，把解码部分注释导出了，所以需要额外用c++写后处理部分。
