### ISSUE TITLE
How to get the pictures with frame as you show

### ISSUE THREAD

**Issue by Chineseddmm** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#48]
Please ,How to get the pictures with frame as you show?

**Comment by Chineseddmm** [comment]
like this [https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/readme_imgs/27.jpg]

**Comment by Linzaer** [comment]
img input_size 640x480 ,threshold is 0.6.

**Comment by Chineseddmm** [comment]
人群图片上标记人脸部分的红色框框是怎么得到的啊，模型训练好了，我想在自己的图片上试试效果

**Comment by Linzaer** [comment]
opencv画，项目里有检测代码。

**Comment by Chineseddmm** [comment]
好的，谢谢
