### ISSUE TITLE
*.onnx模型和*_ncnn.onnx、*_ncnn_slim.onnx模型的区别

### ISSUE THREAD

**Issue by Royzon** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#49]
十分感谢您的工作，对我很有帮助。但我发现针对同一输入尺寸您提供的onnx模型似乎有些细微差别，*.onnx 和 *_ncnn.onnx不能直接转换成ncnn的模型，只有*_ncnn_slim.onnx可以转换而且推理无误，想跟您请教下如何得到*_ncnn_slim.onnx的模型？

**Comment by Linzaer** [comment]
可以查看https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/ncnn 里的readme中的流程。onnx 是包含解码框后处理的，用于pc推理；_nccn.onnx是注释掉后处理部分转换的onnx；_ncnn_slim.onnx是经过onnx-simplifier去冗余后的onnx格式，可以成功转换成ncnn格式。

**Comment by Royzon** [comment]
多谢多谢，都已经成功验证
