### ISSUE TITLE
got errors when loading the weights!!! Help!!!

### ISSUE THREAD

**Issue by yfyan0204** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#5]
Good JOB!!!

But i hit an error when running the detect_imgs.py with cpu， @Linzaer ， can you please help to address the issue?

priors nums:4420
Traceback (most recent call last):
  File "run_video_face_detect.py", line 44, in <module>
    net.load(model_path)
  File "D:\yyf_workspace\Ultra-Light-Fast-Generic-Face-Detector-1MB-master\vision\ssd\ssd.py", line 138, in load
    self.load_state_dict(torch.load(model, map_location=lambda storage, loc: storage))
  File "C:\Users\fkt00044\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SSD:
        Unexpected key(s) in state_dict: "base_net.0.1.num_batches_tracked", "base_net.1.1.num_batches_tracked", "base_net.1.4.num_batches_tracked", "base_net.2.1.num_batches_tracked", "base_net.2.4.num_batches_tracked", "base_net.3.1.num_batches_tracked", "base_net.3.4.num_batches_tracked", "base_net.4.1.num_batches_tracked", "base_net.4.4.num_batches_tracked", "base_net.5.1.num_batches_tracked", "base_net.5.4.num_batches_tracked", "base_net.6.1.num_batches_tracked", "base_net.6.4.num_batches_tracked", "base_net.7.branch0.0.bn.num_batches_tracked", "base_net.7.branch0.1.bn.num_batches_tracked", "base_net.7.branch0.2.bn.num_batches_tracked", "base_net.7.branch1.0.bn.num_batches_tracked", "base_net.7.branch1.1.bn.num_batches_tracked", "base_net.7.branch1.2.bn.num_batches_tracked", "base_net.7.branch2.0.bn.num_batches_tracked", "base_net.7.branch2.1.bn.num_batches_tracked", "base_net.7.branch2.2.bn.num_batches_tracked", "base_net.7.branch2.3.bn.num_batches_tracked", "base_net.7.ConvLinear.bn.num_batches_tracked", "base_net.7.shortcut.bn.num_batches_tracked", "base_net.8.1.num_batches_tracked", "base_net.8.4.num_batches_tracked", "base_net.9.1.num_batches_tracked", "base_net.9.4.num_batches_tracked", "base_net.10.1.num_batches_tracked", "base_net.10.4.num_batches_tracked", "base_net.11.1.num_batches_tracked", "base_net.11.4.num_batches_tracked", "base_net.12.1.num_batches_tracked", "base_net.12.4.num_batches_tracked".
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by Linzaer** [comment]
Is it work well in gpu mode?In general, this is a bit like that the model definition not matching the loaded model parameters.

**Comment by yfyan0204** [comment]
It is failed in windows.
i tried in linux just now, it works well. Great JOB. Thanks.

**Comment by Linzaer** [comment]
@yfyan0204  I just tested detect_imgs.py  in Windows 10 and both cpu and gpu mode worked fine.
env:  win10+pytorch1.2+cuda10.0

**Comment by yfyan0204** [comment]
i have no cuda in win10.

**Comment by Linzaer** [comment]
Cpu mode also works fine.Maybe it’s an environmental issue.

**Comment by yfyan0204** [comment]
Maybe. i'll try with linux. Thx
