### ISSUE TITLE
关于pth和onnx模型所需输入图像预处理步骤不同的问题

### ISSUE THREAD

**Issue by TMaysGGS** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#50]
Linzaer你好，

非常感谢你开源的这个代码。我根据你的代码训练了一个网络，实测效果很好而且也成功转为ONNX格式了。

但我发现PyTorch模型的输入的元素值依旧是0到255之间的，而ONNX模型的输入却必须归一化到 -1到1之间，期间我检查了PyTorch模型的权重参数，与ONNX相同。想请问一下这是什么原因？

另外我因工作任务需要不得不转换模型至Keras的.h5模型，也发现一些问题：
模型结构上看，整个模型的第二层就是Batch Normalization，它需要4个参数：gamma/weight、beta/bias、running_mean和running_var，而第一层就是一个普通的卷积层。
由于PyTorch模型的输入是0到255范围的图像输入，所以第一个卷积层的输出（feature map）也是值横跨范围较大的（已验证）。这种情况下统计出的mean和var往往应该是很大的，mean中最大的值可能会达到100+，而var的值往往会高达1000+。但不管怎样训练从PyTorch模型中查看到的mean和var都是0到1之间的非常小的数， 根据PyTorch的BN层定义，这样是无法批量归一化的，但实际结果是PyTorch用这样小的mean和var能够将大值输入的feature map归一化，而我将权重提取出来实现为Keras的BN层却不能……（两种格式的模型的第一个卷积层输出已验证）。

所以想请问一下PyTorch的Batch Normalization是不是中间包含什么特殊操作（源码看了跟它写的公式明明是一样的）？或者说我是不是对图像输入预处理的步骤理解错误了？

PS：目前已验证的步骤（对比PyTorch和Keras）：1. 测试时的网络输入一致（值相同），经过第一个卷积层后的输入一致。2. 提取PyTorch模型的BN层参数，并根据PyTorch官方文档里的BN层公式来计算输出，输出结果跟Keras模型的BN层输出一致，与PyTorch的BN层输出不一致（但查看结果，显然PyTorch模型的BN层输出是正确的，基本上徘徊在-1~1之间）……3. PyTorch模型的最终输出正确，能够正常找到人脸框。

不好意思问题有点难表达，如果可以希望能有机会进一步询问，非常感谢。

**Comment by Linzaer** [comment]
预处理步骤是有归一化的：lambda img, boxes=None, labels=None: (img / std, boxes, labels)，在data_preprocessing.py里面有哦。

**Comment by TMaysGGS** [comment]
> 预处理步骤是有归一化的：lambda img, boxes=None, labels=None: (img / std, boxes, labels)，在data_preprocessing.py里面有哦。

非常感谢大佬的回复。这段我看到了，我误以为mean始终是0.0，std是1.0了……另外因为net.eval()这个步骤我漏了的缘故导致查看中间层输出的时候BN层根据测试样本做了归一化Orz……

**Comment by noahzhy** [comment]
@TMaysGGS 请问您有转换.h5成功嘛？

**Comment by TMaysGGS** [comment]
> @TMaysGGS 请问您有转换.h5成功嘛？

成功的，一层层取出来再赋值就行。
