### ISSUE TITLE
转化成MNN模型计算计算结果不准确

### ISSUE THREAD

**Issue by zjujeremy** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#52]
我可以将models中onnx模型转化成MNN模型，这样做准确吗？ 转完后发现输出的置信度值不准确（和为1），故请教一下该onnx模型使用方式

**Comment by Linzaer** [comment]
参考项目里ncnn推理实现中的readme步骤。

**Comment by LanWong1** [comment]
![image](https://user-images.githubusercontent.com/33218397/67931146-3f123900-fbfc-11e9-80ca-ebf7a5798561.png)
我的MNN计算也不准确

**Comment by Linzaer** [comment]
@LanWong1  参考下ncnn的步骤和模型，我稍后测试下。个人信息暴露了哈，可以ps下。

**Comment by LanWong1** [comment]
哈哈 这是网上下载的身份证 谢谢提醒啊。 我对输出做了loactions_to_boxes的变换的 因为模型输出的是locations

**Comment by Linzaer** [comment]
好的，五点关键点回归测试加入好后我一并测试下。ncnn目前应该没问题。

**Comment by LanWong1** [comment]
好的 谢谢

**Comment by LanWong1** [comment]
请问一下这个模型转成tflite怎么转啊？我觉得tflite的比较好，我有好几个模型转成mnn都输出不准确，转成tflite就可以

**Comment by zjujeremy** [comment]
请问有转好的pb模型吗

**Comment by Linzaer** [comment]
@zjujeremy 目前没有
