### ISSUE TITLE
Open python inference using ncnn raspberry pi4

### ISSUE THREAD

**Issue by buiduchanh** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#54]
Could you prepare the inference code using python code using ncnn ? 
Thanks

**Comment by Linzaer** [comment]
Does ncnn officially support python inference?

**Comment by buiduchanh** [comment]
> Does ncnn officially support python inference?

Sorry.My mistake. I mean using python with MNN. Thanks

**Comment by Linzaer** [comment]
I will add when I have time.

**Comment by Linzaer** [comment]
[MNN python inference code ](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN/python)
