### ISSUE TITLE
label = f"{class_names[labels[i]]}: {probs[i]: .2f}" error：invalid syntax

### ISSUE THREAD

**Issue by JAYM629** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#55]
How to slove this problems? thank you

**Comment by Linzaer** [comment]
You can use python3.6 or  replace it with  ''{}".format() .

**Comment by JAYM629** [comment]
thank you



发自我的iPhone


------------------ Original ------------------
