### ISSUE TITLE
Should the first dilation rate be 1 in RFB block?

### ISSUE THREAD

**Issue by GatzZ** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#58]
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/3d43e1e71176706d1aa98c17da1a6cdf404212bc/vision/nn/mb_tiny_RFB.py#L40

Since `vision=1`, this `dilation` would become `2`... Not as same as the original paper?

Did you change this value intentionally?

Thanks.

**Comment by Linzaer** [comment]
Yes,change for slim network.

**Comment by GatzZ** [comment]
> Yes,change for slim network.

Solved. Thanks for your explanation.
