### ISSUE TITLE
小问题反馈

### ISSUE THREAD

**Issue by yl305237731** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#6]
nice work👏 最近正好在做人脸检测项目，目前使用的是Retina_face,昨天看见代码，今天正好在实际数据上测试了一下. 总体来说，效果还是很棒的，端正的人脸应该能全检出.  问题主要有两个：1.拍摄时人头部往上仰但人脸完整，召回比较低，0.5左右.  2.测试使用的图片视频比较小，里面的小人脸检测不出来. 这两种情况在我的测试集中retina_face全部都能检测出来.  不过速度确实比Retina_face快多了🎉🎉🎉 其实也不算问题啦，就是实验结果报告😄

**Comment by Linzaer** [comment]
嗯嗯，感谢测试~

- 第一点的话，我倒没太注意这种情况，有空我测试一下，不过你也可以再微调训练下或许有改善。
- 第二点的话是指多大的输入？320x240吗？以我测试比对经验来看的话，retiaface-mobilenet-0.25版本的话在中小分辨率的小人脸检出应该是不如我这个版本的，特别是320x240。大概率是因为训练尺寸原因，我这个默认训练尺寸比较小，更加匹配。你可以尝试降低阈值再试试。同时在检测小分辨图片时，用xxxx_train_input_320.pth名字结尾的模型，适用于320x240小场景的小人脸检出。xxxx_train_input_640.pth的模型在小分辨率场景小人脸检出不如前者。

**Comment by Linzaer** [comment]
@yl305237731 其实从在widerface测试集上在320x240的输入下的精度比对也可以看出，这个模型还是有一定优势的。在比对测试的时候，retinaface也是用的同样大小输入吗？

**Comment by zhanglaplace** [comment]
@yl305237731 你好，你那边测试的速度是多少，我自己在MacOS上测试640的输入大概是160ms/张，模型使用的是浮点的

**Comment by sycophant-stone** [comment]
@zhanglaplace 
模型转换成ncnn在pc上跑也没有优势吧。
ncnn在pc端优化不如嵌入式端吧，可以理解为没怎么优化吧。

**Comment by zhanglaplace** [comment]
@sycophant-stone 嗯，可以这么认为。另外楼主给出的时间是int8模型的时间吧，如果Float的模型时间有吗。

**Comment by yl305237731** [comment]
我测试的视频大小不一，没有resize @Linzaer

**Comment by yl305237731** [comment]
@zhanglaplace 我在macos上测试这个，速度大概是40ms/张，和我GPU上跑Retina_face差不多

**Comment by zhanglaplace** [comment]
@yl305237731 ，我这边跑的是640*480的，RFB模型，我再确认下320*240的Slim模型和RFB的模型时间。多谢～

**Comment by zhanglaplace** [comment]
@yl305237731 刚刚测试了下，320X240的输入，RFB模型52ms，Slim模型45-50ms。。

**Comment by ddcat1991** [comment]
@yl305237731 你好，请问一下你用的Retina_face, 也是纯用widerface训练集训练的吗？

**Comment by yl305237731** [comment]
@ddcat1991 我用的是别人pytorch复现的，和原始的retina_face有点差别. 作者提供了训练好的权重
