### ISSUE TITLE
你好，我这边跑几百次迭代就出现NAN loss可能是什么问题

### ISSUE THREAD

**Issue by gray2bgr** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#60]

**Comment by gray2bgr** [comment]
另外请问这个是SSD的框架么

**Comment by Linzaer** [comment]
自己的数据吗？有可能是数据问题，比如框过小，梯度下降出现问题，检查下数据。
基于ssd改的。

**Comment by gray2bgr** [comment]
@Linzaer 最小的框应该要多少比较合适呢

**Comment by gray2bgr** [comment]
@Linzaer 谢谢你，定位到问题的所在了，我发现我的数据里面含有非正数的标签

**Comment by gray2bgr** [comment]
请问训练过程中有时会出现inf，这种情况合理么

**Comment by Linzaer** [comment]
可能还是小部分数据有问题，会偶尔出现无穷大。或者下调一点lr看看。也可以加上torch.autograd.tect_anomaly来debug看下。

**Comment by torta24x** [comment]
Found my solution here:
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/issues/182#issuecomment-915404168

Hope this helps
