### ISSUE TITLE
关于Widerface测试的问题

### ISSUE THREAD

**Issue by 394781865** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#66]
我训练了一个网络，训练图像都是640*640，我想用你的Widerface测试代码评价自己训练网络的性能。我看见你的代码中都将输入图像resize成320*240，我如何使用640*640的图像进行测试性能呢？

**Comment by 394781865** [comment]
你在widerface数据集上测试，会对输入的图像进行resize吗？我想应该会resize，因为你的anchor是根据输入图像尺寸确定的。但是直接resize会不会导致人脸变形，从而导致精度下降？

**Comment by Linzaer** [comment]
测试的时候保持和你训练的时候一样的缩放策略就好了，我训练的时候是不加pad缩放的，所以测试的时候也一样。网络训练的时候就是拟合的人认为变形的人脸，所以对相同处理流程的图片会更加擅长一点。

**Comment by 394781865** [comment]
wider face数据集的ground truth是原图坐标，你的算法对输入图像进行resize，会导致检测结果与ground truth对不上。当然，可以对检测输出的坐标进行缩放，但是我没看见你的代码里面有这个操作。所以，我猜测你是修改了ground truth吗？

**Comment by Linzaer** [comment]
不是啊，网络训练的都是单位值呀，然后乘图像原大小不就好了，你去看下框解码部分，就是对应原图的大小，当然可以和gt比较呀。
