### ISSUE TITLE
anchor在哪个地方修改

### ISSUE THREAD

**Issue by Zx117x** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#67]
想要修改anchor来训练自己的数据，但是找不到关于anchor的代码

**Comment by Zx117x** [comment]
在box_utils中添加了不同比例的anchor后
报错RuntimeError: The shape of the mask [16, 10820] at index 1 does not match the shape of the indexed tensor [16, 4420] at index 1。
还有哪些其它地方需要修改的

**Comment by Linzaer** [comment]
@Zx117x 还需要改[fd_config.py](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/vision/ssd/config/fd_config.py)里面的anchor相关参数。

**Comment by Zx117x** [comment]
> @Zx117x 还需要改fd_config.py里面的anchor相关参数。

mb_tiny_fd.py里的regression_headers和classification_headers不用修改吗

**Comment by Linzaer** [comment]
如果你改了每个headers上的anchor数目的话，那边的输出channels数量修改下就好了，如果你只是改了anchor的纵横比的话不需要。

**Comment by Zx117x** [comment]
> 如果你改了每个headers上的anchor数目的话，那边的输出channels数量修改下就好了，如果你只是改了anchor的纵横比的话不需要。

明白了，感谢
