### ISSUE TITLE
关于输入大小和retinaface 的问题

### ISSUE THREAD

**Issue by yushanhu12345** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#7]
想问下我的理解对不对：
1.wider face的结果，这里提到的input 320*240 和 640*480是专指训练的时候的大小吗，inference的时候直接输入原图对吧？
2.mobilenev1_0.25版的retinaface先按照640*480的训练，再在原图上inference得到 0.879 | 0.807 | 0.481的结果吗？

**Comment by Linzaer** [comment]
用640x480输入推理

**Comment by Linzaer** [comment]
我测的是固定中小输入下的精度，现实场景一般都是固定大小输入，比如320或者640

**Comment by yushanhu12345** [comment]
@Linzaer 
wider face测试的图片和./imgs目录下的图片不是固定输入大小，detect_img.py run_video_face_detect.py里并没有resize操作而是直接读取图片再predict。
所以我不太明白的是，用640*480的输入推理是怎么在wider face和./imgs目录下的图片进行推理的？

**Comment by Linzaer** [comment]
@yushanhu12345 有resize的哦，在PredictionTransform里，封装到预处理里了

**Comment by yushanhu12345** [comment]
@Linzaer 
哦，明白了！
难怪很多大图识别效果不好，准备尝试一下把大图crop出几个vga的tile分别predict，效果应该会好不少

**Comment by Linzaer** [comment]
可以尝试修改图片输入大小，比如detect_imgs.py里面修改开头第11行的input_img_size，可以适当加大。同时如果你想识别大图小人脸场景，建议使用 Mb_Tiny_RFB_FD_train_input_640.pth这个模型，是用640x480训练的，更加适合大分辨率输入，误报低。

**Comment by yushanhu12345** [comment]
@Linzaer 
自己训练的一些模型和你这个模型，好像都有个问题，就是用大分辨率训练的模型，误检少，对小脸的recall低，
用小分辨率训练的模型，误检多，对小脸的recall高。
刚用Mb_Tiny_RFB_FD_train_input_320.pth和Mb_Tiny_RFB_FD_train_input_640.pth测试过，其他条件都一样（输入640×480的图片，从原图上crop， threshold=0.3）

**Comment by Linzaer** [comment]
@yushanhu12345 一般来说是都这样的，应该是不同大小输入训练的感受野对应原图大小区域的问题。

**Comment by Jay-Liu** [comment]
来围观一下大神@-@

**Comment by Linzaer** [comment]
@Jay-Liu 没没没，我也在学习中，也都是在其他大佬的肩膀上玩，开源就是和大家互相交流学习哈~

**Comment by Jay-Liu** [comment]
还是好厉害，高山仰止。

**Comment by leiyu1980** [comment]
可以说说训练这个检测器的心得嘛。效果确实不错，速度也快。

**Comment by Linzaer** [comment]
@leiyu1980 其实也没啥，就是不断调参压榨结构哈哈哈，就还是炼丹^-^

**Comment by nttstar** [comment]
问一下anchor是如何设置的?

**Comment by Linzaer** [comment]
@nttstar 大佬好~anchor设计参考了于老师的libfacedetection,四分支3/2/2/3个数配比，加强小人脸和大人脸能力。320x240输入得到的四个feature尺寸(40,20,10,5）,然后8*n关系设置大小，每层2倍增加。我也用check_gt_box.py得到训练集的尺寸分布调整过数值，效果差不多。

**Comment by tfygg** [comment]
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/52e5c8b8b719538a0af87755614c930a31484afb/vision/transforms/transforms.py#L401

有个疑惑，如上代码是crop出一个h=w的正方形图像，数据扩展也没有padding的过程，那这样在直接resize后人脸会有形变呀。

**Comment by Linzaer** [comment]
@tfygg 你好，由于人脸主要贴近正方形，所以选的纵横比是1，但是能等于1 的时候几率是非常低的，几乎不会进入下面的randomcrop，所以绝大部分数据几乎是原图，而且就等于1，resize形变也会可以接受的，因为即使有Expand，当randomcrop出小区域的不同比例的时候，resize之后也是会形变的。由于模型比较小，所以没采用Expand去放大来加强小人脸检出能力，测试调参发现去掉Expand效果会好点,可能是原本数据集的小人脸就已经足够去拟合了。不过这是我的测试结果和想法，你也可以去调参试试~期待好的结果

**Comment by HuColin** [comment]
> @tfygg 你好，由于人脸主要贴近正方形，所以选的纵横比是1，但是能等于1 的时候几率是非常低的，几乎不会进入下面的randomcrop，所以绝大部分数据几乎是原图，而且如果等于1，resize一定的形变也是可以接受的，因为即使有Expand，当randomcrop出小区域的不同比例的时候，resize之后也是会形变的。由于模型比较小，所以没采用Expand去扩展原图来加强小人脸检出能力，测试调参发现去掉Expand效果会好点,可能是原本数据集的小人脸就已经足够去拟合了。不过这是我的测试结果和想法，你也可以去调参试试~期待更好的结果。

作者您好，这里如果使用裁剪的1:1的图片或者使用原始图片在进行resize的过程中bbox的数值不需要跟随resize一起变化吗？我看数据读取流程是在`VOCDataset`中的`__getitem__`函数里调用`_get_annotation`获取boxes的左上角和右下角的坐标
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/96f430f4e2ce376752baa949528e50290808cdb0/vision/datasets/voc_dataset.py#L55
这里读取了图片和标注后，就对数据进行预处理，在里面进行图片的resize前，bbox的数值似乎还没有进行归一化
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/96f430f4e2ce376752baa949528e50290808cdb0/vision/datasets/voc_dataset.py#L61
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/96f430f4e2ce376752baa949528e50290808cdb0/vision/ssd/data_preprocessing.py#L13-L23
进行裁剪或是后续进行resize的话，bbox的实际值不需要进行相应的处理吗？因为后面实际进行` ToPercentCoords`操作的时候使用的是resize后的图片宽高，这个时候实际得到的bbox已经和原图已经对不上了吧？
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/96f430f4e2ce376752baa949528e50290808cdb0/vision/transforms/transforms.py#L126-L134
