### ISSUE TITLE
Question about ncnn2int8

### ISSUE THREAD

**Issue by zxb-caffe** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#73]
I followed the ncnn tutorial to quantify the ncnn.bin and ncnn.param you provided. Successfully got the bin and param of int8. Then use int8 when inferring, the result will be an error. Excuse me, have you quantified it?

**Comment by Linzaer** [comment]
I also encountered an error and  it has not been resolved yet.
