### ISSUE TITLE
有没有cpu版本的？如何转到andorid系统里面呢？小白发问。

### ISSUE THREAD

**Issue by Ichzhang** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#8]
不好意思，找过的其它版本是C或者C++的，可以转cmake到andriod系统中，但py怎么转没做过。找过一些文章转各种出错。

**Comment by Linzaer** [comment]
@Ichzhang 你可以试试MNN、NCNN推理框架，这段时间有空的时间在写这几个推理框架的c++代码，写好了会放上来~
