### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by aichaoGitHub** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#81]
请问一下这种轻量化的模型可以训练其它对象吗？除了人脸还可以检测，猫狗吗？

**Comment by Linzaer** [comment]
可以的。更换数据集、并且针对训练数据特点修改调整anchor和预处理流程就可以了。

**Comment by aichaoGitHub** [comment]
好的谢谢，虽然是这个意思，但是对于我来讲还是太复杂，您这边有没有类似的开源项目学习一下呀？

**Comment by Linzaer** [comment]
你可以看下ssd的训练代码。

**Comment by aichaoGitHub** [comment]
谢谢，用SSD训练的模型也是这种轻量化的吗？不会像yolo啥的很庞大，检测速度很慢吧？

**Comment by Linzaer** [comment]
默认主干比较大，需要修改。
