### ISSUE TITLE
multi-target detection

### ISSUE THREAD

**Issue by yufeilongyuan** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#82]
If I want to change to multi-target detection, where should I change the code? Is it significant?

**Comment by Linzaer** [comment]
Do you mean multi-category detecting?If so, you need to modify the category tags , anchor strategy,  detection headers and image preprocessing process.

**Comment by yufeilongyuan** [comment]
That's exactly what I think. Thank you very much for your suggestion. I will change your code to multi-target detection. If there are any unsolvable problems, I will ask you for help as soon as possible. Finally, thank you. Your code is excellent and enlightening. Thank you.
