### ISSUE TITLE
windows 和 linux 测试（训练）时间差距很大

### ISSUE THREAD

**Issue by Belinda-great** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#84]
Windows下测试时间非常慢， pc: win7 cpu E5-1603 2.80GHz ,net_type: mb_tiny_fd, input_size:320,图片大小为320*240，测试14张图片，平均时间为：203ms, centos7上时间就很快 差不多14ms 训练也是差别很大 在centos7训练很快 Windows下就超级慢， 请问大概是什么原因那？

**Comment by Linzaer** [comment]
可能是pytorch的cpu实现在你这个win硬件平台下效果不好，而且还是你这个老版本的服务器的u。我用的相同的i7-8700的u在win10和ubuntu下pytorch-cpu模式跑速度差不多都是10ms左右，320输入。如果要部署的话，移动端建议mnn或者ncnn，pc cpu建议openvino或者mnn, gpu端建议tensorrt。

**Comment by Belinda-great** [comment]
> 可能是pytorch的cpu实现在你这个win硬件平台下效果不好，而且你这个还是老版本的服务器u。我用的相同的i7-8700的u在win10和ubuntu下pytorch-cpu模式跑速度差不多都是10ms左右，320输入。如果要部署的话，移动端建议mnn或者ncnn，pc cpu建议openvino或者mnn, gpu端建议tensorrt。

非常不错的建议 万分感谢！
