### ISSUE TITLE
Caffe model in opencv

### ISSUE THREAD

**Issue by pjspillai** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#85]
I tried running the converted caffe models via opencv dnn caffe script and am unable to interpret the results.

Ideally the detection outputs from the forward pass during inference should be a set of bboxes, conf.. predictions.
But what I am receiving is a list of (1, 13242, 2) values. What do these represent exactly?

```
self.net = dnn.readNetFromCaffe(self.prototxt_file, self.model_pathinp_width =480, inp_height = 480)
self.net.setInput(dnn.blobFromImage(frame, 1.0, (self._f_width, self._f_height), (self._m1, self._m2, self._m3), False, False))
self.detections = self.net.forward()
print(np.shape(self.detections))
```

**Comment by Linzaer** [comment]
The converted caffe model does not contain the detectionout layer，the outputs has two arrays, one is  scores(1,4420,2) and the other is boxes(1,4420,4)，so you need to add the post processing.

**Comment by pjspillai** [comment]
Thanks! 

I am getting outputs in the following form:

-0.06667982 -0.58126396 -1.1865556 -0.27930307
-0.086416796 -0.89094937 -1.3859854 -0.5046445
0.049911253 -0.33554888 -1.1623797 -0.08576904
0.06991154 -0.5340975 -1.2665751 -0.25954255
0.05625076 -0.8642361 -1.4737158 -0.5085962
0.016570471 -0.38922626 -1.5873095 -0.37555012

are these in the scaled form (xc, yc, w, h) ?

**Comment by Linzaer** [comment]
@pjspillai This is the coordinates of the center point format before post-processing. You can refer to my implementation of post-processing in  [Python implemententation of this project  with MNN](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN/python).

**Comment by pjspillai** [comment]
There are discrepancies in the model output caffe vs pytorch for a given image.
I tried modifying the Predictor class from vision.ssd.predictor.py and do the post processing of the boxes and scores.
I made sure that the image preprocessing steps, nms params, thresholds, img size, is al matching. But couldn't figure out why the detection outputs are so different!

**Comment by Linzaer** [comment]
I previously tested that the caffe model can be converted into the ncnn model normally and inference  normally. When I have time I will run this model in caffe .

**Comment by Linzaer** [comment]
@pjspillai .I just tested it, and the caffe inference results are normal.

**Comment by Linzaer** [comment]
@pjspillai . I uploaded the [caffe inference code](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/caffe/ultra_face_caffe_inference.py).

**Comment by pjspillai** [comment]
Thanks Linzaer!

I was referring to the **opencv DNN module (ONNX, Caffe) ** and loading the models there directly.

I made slight modifications to your code, and getting empty bounding boxes after the post processing

`def inference():

    net = dnn.readNetFromCaffe(caffe_prototxt_path, caffe_model_path)

    input_size = [int(v.strip()) for v in args.input_size.split(",")]
    witdh = input_size[0]
    height = input_size[1]
    priors = define_img_size(input_size)

    img_ori = cv2.imread(imgs_path)

    print(np.shape(img_ori))
    tmp_batch = np.zeros([1, 3, height, witdh], dtype=np.float32)
    image = cv2.resize(img_ori, (witdh, height))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    # image = (rect - image_mean) / image_std
    # tmp_batch[0, :, :, :] = image.transpose(2, 0, 1)
    # image = image.astype(np.uint8)
    # print((image.dtype))

    net.setInput(dnn.blobFromImage(image, 1.0, (witdh, height), (127, 127, 127), False, False))

    # net.blobs['input'].data[...] = tmp_batch
    time_time = time.time()
    # scores = net.forward()['scores'][0]
    # boxes = net.forward()['boxes'][0]
    boxes, scores = net.forward(["boxes", "scores"])

    boxes = boxes[0]
    scores = scores[0]

    print(boxes)
    print("inference time: {} s".format(round(time.time() - time_time, 4)))
    boxes = np.expand_dims(np.reshape(boxes, (-1, 4)), axis=0)
    scores = np.expand_dims(np.reshape(scores, (-1, 2)), axis=0)
    boxes = convert_locations_to_boxes(boxes, priors, center_variance, size_variance)
    boxes = center_form_to_corner_form(boxes)
    boxes, labels, probs = predict(img_ori.shape[1], img_ori.shape[0], scores, boxes, threshold)
    print(boxes.shape[0])
`

**Comment by Linzaer** [comment]
Change `net.setInput(dnn.blobFromImage(image, 1.0, (witdh, height), (127, 127, 127), False, False))` to`net.setInput(dnn.blobFromImage(image,  **0.0078125** , (witdh, height), (127, 127, 127), False, False))`

**Comment by pjspillai** [comment]
It works beautifully! Thanks so much!
