### ISSUE TITLE
MNN i7-8700多核推理耗时40ms

### ISSUE THREAD

**Issue by jianxiezhendong** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#87]
在pc i7-8700下使用MNN推理，默认多核进行，运行官方例程RFB-int8量化模型，每张图片耗时40ms，运行速度较慢，请问是什么原因呢？

**Comment by Linzaer** [comment]
mnn pc下用fp32模型，int8在pc下优化不好反而慢。我这边ubuntu/i7-8700/320x240/RFB/4核推理是3ms左右，slim版本是2ms左右.

**Comment by jianxiezhendong** [comment]
4核？请问你是怎么选择使用的核数的，谢谢了

**Comment by Linzaer** [comment]
c++ 例子是在示例初始化那边设置，默认4。python版本的话从cpu使用率看默认应该是4核。
