### ISSUE TITLE
关于模型优化的几个问题

### ISSUE THREAD

**Issue by lexuszhi1990** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#88]
首先感谢分享这个代码，很简洁，效果很好。关于现有模型我有几个问题
- 用 blazeface 模型，优化速度
- 300VW 视频人脸数据集
- 模型只用正方形框来预测人脸，anchor 长宽比只设置为1：1

据说blazeface的模型速度很快，打算在这个基础上测试以下，不知测试过没有
另外，在移动端，人脸检测大多用于视频情况，这个时候检测框的抖动会非常明显，一般有两个解决思路，1）用视频数据来训练 2）用跟踪来代替一部分检测。
最后就是 人脸形变不会很大，是不是用正方形来预测即可，一方面可以提升速度，另一方面正方形可以直接用于人脸关键点检测

这三点是我的一些问题，谢谢

**Comment by Linzaer** [comment]
@lexuszhi1990 感谢提的问题。

1. 根据从测试的MNN推理测试结果来看，骁龙625单核在相同128x128输入分辨率下FP32精度，ultra-face 推理延迟（9ms）是blazeface(19ms)的一半，四核同理（3ms vs 6ms）。
2. 正方形训练当然可以，主要还是看图像预处理阶段的操作，比如加不加pad缩放，crop策略等。在保证最大边一样的情况下，长方形分辨率是低于正方形的，计算量因此也会小一点。至于关键点回归和坐标点同理，长方形同样可以训练。
3. 一般视频检测都会加一定程度的追踪，一方面是为了节省算力，一方面也是为了去重提优，这方面也可以参考我另一个开源项目。

希望对你有帮助，谢谢。

**Comment by lexuszhi1990** [comment]
非常感谢你的回复。首先 感觉mnn速度要比ncnn快很多啊，ncnn这边目测以128x96输入，耗时也没有到9ms，而且ncnn 多核的话，速度并没有上升，反而是发热严重。
第二点你好像理解错我的问题了，我本来是想，把人脸的label都修改为正方形，然后 anchor 的长宽比也只设成 1:1，这样出来的候选框就少很多了。图片的输入还是跟之前的一样就行。
第三点，我看了你另外一个项目，使用kalman滤波来做的，所以我想问下选择kalman的原因，kalman filter 和 kcf有做过对比吗？

**Comment by Linzaer** [comment]
1.至少这个模型在mnn上还是要相对快的，优化相对要好一些。
2.目前的anchor的纵横比就是只有1:1的，而且每个检出层featuremap的单位点分配的anchor数量都调整减少的。由于训练是不加pad resize的，对训练尺寸拟合的比较好，所以如果预测用正方形的话，可能预测框回归会有一定的偏差。
3.kaiman适合运动趋势规律的物体的追踪场景，计算速度快，资源消耗小，在低端低算力的cpu上例如A53之类的可以不到1ms把多目标预测完，配合sort，算是一个折中方案吧。kcf在资源有限的场景中个人测下来做多目标追踪效果不好。

**Comment by lexuszhi1990** [comment]
非常感谢，希望以后多多交流
