### ISSUE TITLE
有FDDB上的测试结果吗?

### ISSUE THREAD

**Issue by sharepointer** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#89]

**Comment by Linzaer** [comment]
暂时还没有。

**Comment by sharepointer** [comment]
方便加上吗? 谢谢~

另外请教一下,像固定尺寸输入的网络,在类似FDDB的数据集测试,如果直接加pad等比例缩放合适吗?(训练的时候随机crop等比例缩放),会增加小人脸的检测难度影响评测......

**Comment by Linzaer** [comment]
预测和训练流程匹配就可以。

**Comment by AlexJunCpp** [comment]
我这边测的FDDB的结果并不是很好，请问还有其他人测过吗

**Comment by fengyanWang** [comment]
> 我这边测的FDDB的结果并不是很好，请问还有其他人测过吗

我用作者开源出的预训练模型测了一下，下面是结果
version-RFB-320
outputsContROC：
![outputsContROC](https://user-images.githubusercontent.com/36984088/131964452-408f097b-0016-475f-a658-00e9cc7908e0.png)
outputsDiscROC
![outputsDiscROC](https://user-images.githubusercontent.com/36984088/131964419-4cbab1b9-83d0-4fd0-8733-c979be30ac8a.png)

version-slim-320
outputsDiscROC
![outputsDiscROC](https://user-images.githubusercontent.com/36984088/131964514-222a19d6-65eb-47ed-87cc-f1ee01094217.png)
outputsContROC
![outputsContROC](https://user-images.githubusercontent.com/36984088/131964538-02c8c179-6594-436a-931e-4cfecc3886cf.png)
