### ISSUE TITLE
caffe 训练文件

### ISSUE THREAD

**Issue by xdg2016** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#90]
您好，请问有caffe的训练文件吗？我看了下模型和deploy文件，没有发现哪里可以设置anchor,也没有特殊层，比如SSD的DetectionOutput层，全部都是卷积，relu,concat，想看下训练文件是什么样的，谢谢！

**Comment by Linzaer** [comment]
这个caffe模型不是训练的，是用从onnx转换的，转换代码给了。
