### ISSUE TITLE
如果按照原始的采用320x320的输入训练模型，效果怎么样呢? 

### ISSUE THREAD

**Issue by SyGoing** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#91]
看了下你的代码，训练的输入上类似libfacedetection ,采用320x240，原始的ssd一般都是w=h的训练，改为320x240是训练的效果会更好么，求作者告知

**Comment by Linzaer** [comment]
你好，输入采用正方形比如320x320或者640x640的也训练过几版，在widerface val集上320x320输入训练的得分（0.80/0.72/0.449）相比320x240输入训练的得分（0.787/0.698/0.438）提高了1%~2%左右，但是计算量多了33%，109MFlops->144.94MFlops，所以权衡之下还是选择了计算量更小的输入训练。另外我平时的一个图片推理场景也是偏向于4:3长宽比的输入，所以个人认为这个比例训练对预测的拟合性会更好一点。这个模型主要还是针对中小输入优化的，当然也可以用其他图片预处理流程+正方形训练，效果可能会更好一点。
