### ISSUE TITLE
compile libMNN.so parameters

### ISSUE THREAD

**Issue by jackweiwang** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#92]
i want compile android libMNN.so by mnn source code, 
but compile version, can't  be used RFB-300.mnn.

run in android  crash at createSession()

log
**-------- beginning of main
11-28 14:56:49.925 23534 23534 D FaceSDKNative: init, tFaceModelDir=/storage/emulated/0/facesdk/RFB-320.mnn
--------- beginning of crash
11-28 14:56:49.958 23534 23534 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23534 (com.facesdk)
11-28 14:56:50.061   544   544 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-28 14:56:50.061   544   544 F DEBUG   : Build fingerprint: 'Lenovo/phinny_prc/PB2PRO:6.0.1/MMB29M/PB2-690N_S200027_161214:user/release-keys'
11-28 14:56:50.061   544   544 F DEBUG   : Revision: '0'
11-28 14:56:50.062   544   544 F DEBUG   : ABI: 'arm'
11-28 14:56:50.062   544   544 F DEBUG   : pid: 23534, tid: 23534, name: com.facesdk  >>> com.facesdk <<<
11-28 14:56:50.062   544   544 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-28 14:56:50.073   544   544 F DEBUG   :     r0 00000000  r1 ab5168d0  r2 1474c4c1  r3 00000000
11-28 14:56:50.073   544   544 F DEBUG   :     r4 1474c4c1  r5 fff26920  r6 00000003  r7 00000000
11-28 14:56:50.073   544   544 F DEBUG   :     r8 00000000  r9 ab2c9180  sl fff26870  fp ab2c9180
11-28 14:56:50.073   544   544 F DEBUG   :     ip 00000000  sp fff267a8  lr ef4b4105  pc ef4baff8  cpsr 600f0030
11-28 14:56:50.076   544   544 F DEBUG   :
11-28 14:56:50.076   544   544 F DEBUG   : backtrace:
11-28 14:56:50.076   544   544 F DEBUG   :     #00 pc 0000aff8  /data/app/com.facesdk-1/lib/arm/libfacedetect.so (Java_com_facesdk_FaceSDKNative_FaceDetectionModelInit+331)
11-28 14:56:50.076   544   544 F DEBUG   :     #01 pc 000ea8e9  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
11-28 14:56:50.076   544   544 F DEBUG   :     #02 pc 000e61f1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
11-28 14:56:50.076   544   544 F DEBUG   :     #03 pc 003eb523  /system/lib/libart.so (art_quick_invoke_stub+170)
11-28 14:56:50.076   544   544 F DEBUG   :     #04 pc 007fc99c  [stack]
11-28 14:56:50.185  5033  5033 D RecentsTaskLoadPlan: [ALWAYS] [preloadPlan] preloadPlan taskCount = 1; isTopTaskHome = true
11-28 14:56:50.195  5033  5033 D RecentsTaskLoadPlan: [ALWAYS] [preloadPlan] preloadPlan task packageName = com.facesdk
11-28 14:56:50.204   544   544 F DEBUG   :
11-28 14:56:50.204   544   544 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
11-28 14:56:50.204   544   544 E DEBUG   : AM write failed: Broken pipe
--------- beginning of system
**

**Comment by Linzaer** [comment]
Maybe you can write an issue to MNN github.

**Comment by jackweiwang** [comment]
Yes,  I want to  know,  if you've  used android demo it.

**Comment by jackweiwang** [comment]
I solved,  but the same model has different precision in android and pc , the issues closed.
