### ISSUE TITLE
PC端的MMN的问题

### ISSUE THREAD

**Issue by zhongwenkun886** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#96]
在PC端和Android端跑本项目提供的MNN的DEMO，当把初始化 UltraFace 时的 input_size 设为640时，输出结果会严重错误，input_size默认为320时没问题。

**Comment by Linzaer** [comment]
@zhongwenkun886 感谢提出问题，bug已经修复了，是由于没有resize input_tensor导致的，并且优化了部分代码。
