### ISSUE TITLE
在mb_tiny.py中的错误

### ISSUE THREAD

**Issue by jaffe-fly** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#97]
def forward(self, x):
        x = self.model(x)#torch.Size([1, 256, 10,8])
        x = F.avg_pool2d(x, 7)#torch.Size([1, 256, 1, 1])
        x = x.view(-1, 1024)
        x = self.fc(x)
        return x
平均池化后的图片尺寸为1*1，通道为256，所以view的时候没办法变成1024
其他人有遇到过这种问题吗？

**Comment by Linzaer** [comment]
这边你自己调整一下就好了，这是默认mb的，这部分没用到我就没改。
